# Generated by Django 6.1.1 on 2026-09-23 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=48, unique=True, verbose_name='批次号')),
                ('product', models.CharField(default='某型组件', max_length=64, verbose_name='产品型号')),
                ('line', models.CharField(default='一号线', max_length=64, verbose_name='产线')),
                ('planned_qty', models.PositiveIntegerField(default=0, verbose_name='计划数量')),
                ('produced_at', models.DateField(verbose_name='投产日期')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '产品批次',
                'verbose_name_plural': '产品批次',
                'ordering': ['-produced_at', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='缺陷编号')),
                ('name', models.CharField(max_length=64, verbose_name='缺陷名称')),
                ('category', models.CharField(blank=True, max_length=64, verbose_name='缺陷大类')),
                ('severity', models.CharField(choices=[('minor', '轻微'), ('major', '一般'), ('critical', '严重')], default='major', max_length=16, verbose_name='严重度')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用中')),
            ],
            options={
                'verbose_name': '缺陷类型',
                'verbose_name_plural': '缺陷类型',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='工位编号')),
                ('name', models.CharField(max_length=64, verbose_name='工位名称')),
                ('line', models.CharField(default='一号线', max_length=64, verbose_name='所属产线')),
                ('operator', models.CharField(blank=True, max_length=64, verbose_name='负责师傅(化名)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='工序顺序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用中')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '工位',
                'verbose_name_plural': '工位',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_qualified', models.BooleanField(default=True, verbose_name='是否合格')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='本条记录数量')),
                ('serial', models.CharField(blank=True, max_length=64, verbose_name='产品/工单编号(虚构)')),
                ('inspector', models.CharField(blank=True, max_length=64, verbose_name='质检员(化名)')),
                ('inspected_at', models.DateTimeField(verbose_name='检验时间')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='录入时间')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='board.batch', verbose_name='批次')),
                ('defect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='board.defect', verbose_name='缺陷类型')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='board.station', verbose_name='工位')),
            ],
            options={
                'verbose_name': '质检记录',
                'verbose_name_plural': '质检记录',
                'ordering': ['-inspected_at'],
                'indexes': [models.Index(fields=['station', 'inspected_at'], name='board_inspe_station_dd5016_idx'), models.Index(fields=['batch', 'is_qualified'], name='board_inspe_batch_i_258329_idx')],
            },
        ),
    ]
